[package]
name = "either"
version = "1.13.0"
authors = ["bluss"]
edition = "2018"
rust-version = "1.37"

license = "MIT OR Apache-2.0"
repository = "https://github.com/rayon-rs/either"
documentation = "https://docs.rs/either/1/"
readme = "README-crates.io.md"

description = """
The enum `Either` with variants `Left` and `Right` is a general purpose sum type with two cases.
"""

keywords = ["data-structure", "no_std"]
categories = ["data-structures", "no-std"]

[dependencies]
serde_internal = { package = "serde", version = "1.0", optional = true, features = ["derive"] }
serde_derive = { version = "=1.0.156", optional = true }
proc-macro2 = { version = "=1.0.65", optional = true }

[features]
default = ["use_std"]
use_std = []
serde = ["serde_internal", "serde_derive", "proc-macro2"]

[dev-dependencies]
serde_json = "1.0.0"

[package.metadata.release]
no-dev-version = true
tag-name = "{{version}}"

[package.metadata.docs.rs]
features = ["serde"]

[package.metadata.playground]
features = ["serde"]
